import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiGo,
  SiRust,
  SiCplusplus,
  SiC,
  SiSharp,
  SiRuby,
  SiPhp,
  SiSwift,
  SiKotlin,
  SiHtml5,
  SiCss,
  SiSass,
  SiLess,
  SiGnubash,
  SiPowers,
  SiDocker,
  SiYaml,
  SiJson,
  SiMarkdown,
  SiLatex,
  SiScala,
  SiElixir,
  SiClojure,
  SiHaskell,
  SiLua,
  SiDart,
  SiR,
  SiJulia,
  SiPerl,
  SiZig,
  SiNim,
  SiSolidity,
  SiAssemblyscript,
  SiVuedotjs,
  SiSvelte,
  SiAstro,
  SiGraphql,
  SiPostgresql,
  SiPrisma,
  SiProtocolsdotio,
  SiCodefactor,
} from "react-icons/si"
import type { IconType } from "react-icons"

const icons: Record<string, IconType> = {
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Python: SiPython,
  Java: SiCodefactor,
  Go: SiGo,
  Rust: SiRust,
  "C++": SiCplusplus,
  C: SiC,
  "C#": SiSharp,
  Ruby: SiRuby,
  PHP: SiPhp,
  Swift: SiSwift,
  Kotlin: SiKotlin,
  HTML: SiHtml5,
  CSS: SiCss,
  SCSS: SiSass,
  Less: SiLess,
  Shell: SiGnubash,
  PowerShell: SiPowers,
  Dockerfile: SiDocker,
  YAML: SiYaml,
  JSON: SiJson,
  Markdown: SiMarkdown,
  TeX: SiLatex,
  Scala: SiScala,
  Elixir: SiElixir,
  Clojure: SiClojure,
  Haskell: SiHaskell,
  Lua: SiLua,
  Dart: SiDart,
  R: SiR,
  Julia: SiJulia,
  Perl: SiPerl,
  Zig: SiZig,
  Nim: SiNim,
  Solidity: SiSolidity,
  Assembly: SiAssemblyscript,
  "Objective-C": SiCodefactor,
  Vue: SiVuedotjs,
  Svelte: SiSvelte,
  Astro: SiAstro,
  GraphQL: SiGraphql,
  SQL: SiPostgresql,
  Prisma: SiPrisma,
  "Protocol Buffer": SiProtocolsdotio,
}

const colors: Record<string, string> = {
  JavaScript: "#f7df1e",
  TypeScript: "#3178c6",
  Python: "#3572a5",
  Java: "#b07219",
  Go: "#00add8",
  Rust: "#dea584",
  "C++": "#f34b7d",
  C: "#555555",
  "C#": "#178600",
  Ruby: "#701516",
  PHP: "#4f5d95",
  Swift: "#f05138",
  Kotlin: "#a97bff",
  HTML: "#e34c26",
  CSS: "#563d7c",
  SCSS: "#c6538c",
  Less: "#1d365d",
  Shell: "#89e051",
  PowerShell: "#012456",
  Dockerfile: "#384d54",
  YAML: "#cb171e",
  JSON: "#292929",
  Markdown: "#083fa1",
  TeX: "#3d6117",
  Scala: "#c22d40",
  Elixir: "#4e2a59",
  Clojure: "#db5855",
  Haskell: "#5e5086",
  Lua: "#000080",
  Dart: "#00b4ab",
  R: "#198ce7",
  Julia: "#a270ba",
  Perl: "#0298c3",
  Zig: "#ec915c",
  Nim: "#ffc200",
  Solidity: "#6c6c6c",
  Assembly: "#6e4c13",
  "Objective-C": "#438eff",
  Vue: "#41b883",
  Svelte: "#ff3e00",
  Astro: "#ff5a03",
  GraphQL: "#e10098",
  SQL: "#e38c00",
  Prisma: "#2d3748",
  "Protocol Buffer": "#6c6c6c",
}

export function LanguageIcon({ language, className }: { language: string; className?: string }) {
  const Icon = icons[language]
  if (!Icon) return null
  return <Icon className={className} style={{ color: colors[language] }} />
}
